services:
  my-server:
    build: .
    container_name: rehab-server
    ports:
      - "8080:8080"
    depends_on:
      my-cache-server:
        condition: service_healthy
    networks:
      - backend-net

  my-cache-server:
    image: redis:latest
    container_name: rehab-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

