services:
  my-server:
    build: .
    container_name: rehab-server
    ports:
      - "8080:8080"
    mem_limit: 768m
    environment:
      SPRING_REDIS_HOST: my-cache-server
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms256m -Xmx512m"

    depends_on:
      my-cache-server:
        condition: service_healthy
    networks:
      - backend-net

  my-cache-server:
    image: redis:latest
    container_name: rehab-redis
    mem_limit: 192m
    command: >
      redis-server
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

